-- DUMMY DATA SEED SCRIPT
-- Run this in the Supabase SQL editor AFTER running supabase_schema.sql

-- 1. Insert Dummy Charities
INSERT INTO public.charities (name, slug, description, is_featured, is_active, total_contributions)
VALUES 
('Fore The Kids Foundation', 'fore-the-kids', 'Providing youth programs and mentorship by using the rules of the game to teach life skills. Every subscription actively funds community youth outreach.', true, true, 420.50),
('Green Drives Initiative', 'green-drives', 'Dedicated to planting trees and maintaining ecological conservation across global community parks.', false, true, 115.00),
('Golfers Against Hunger', 'golfers-against-hunger', 'A global initiative pooling resources to support local food banks and end hunger in underprivileged neighborhoods.', false, true, 890.25)
ON CONFLICT (slug) DO NOTHING;

-- 2. Insert Prize Pool Config
INSERT INTO public.prize_pool_config (effective_from, match_5_pct, match_4_pct, match_3_pct, subscription_pool_pct, charity_min_pct)
VALUES 
(CURRENT_DATE, 40, 35, 25, 60, 10);

-- Note: To create an Admin User, you must first create an Auth account on the frontend (or via Supabase Auth UI),
-- then take the UUID generated by Supabase Auth and run:
-- UPDATE public.profiles SET role = 'admin', subscription_status = 'active', subscription_plan = 'yearly' WHERE email = 'YOUR_EMAIL@example.com';

-- 3. (Optional) Insert Dummy Scores for a specific user ID if you have one. 
-- Replace 'USER_UUID_HERE' with an actual user string from auth.users.
-- INSERT INTO public.scores (user_id, score, played_at) VALUES
-- ('USER_UUID_HERE', 36, '2026-03-01'),
-- ('USER_UUID_HERE', 28, '2026-03-05'),
-- ('USER_UUID_HERE', 32, '2026-03-12');
